### ISSUE TITLE
Use official mavlink dialect?

### ISSUE THREAD

**Issue by jodersky** [project-condor/mavigator#5]
In view of portability, it might be best to adopt an official MAVLink dialect or support a subset thereof. There'll have to be further consideration in choosing which one and or what messages, feel free to comment.

**Comment by chernetsov** [comment]
Vote up for official dialect. Will start playing with it in my fork.

**Comment by jodersky** [comment]
Cool!
While moving the mavlink plugin to a separate project I ran into some issues testing the official 'common' dialect. You'll also get these errors when you'll change the mavlink dialect definition in this project.
However, it should be fixed now, so please pull again or update the project/plugins file:
`addSbtPlugin("com.github.jodersky" % "sbt-mavlink" % "0.2")`

**Comment by jodersky** [comment]
Hey, I don't mean to interfere with an issue you've taken up but I saw you haven't committed any changes on your fork yet. So I just wanted to tell you that I updated the MAVLink plugin and successfully managed to compile against the official "common" dialect.

See the branch [wip/mavlink-commn](https://github.com/jodersky/vfd/tree/wip/mavlink-common).

The branch is work-in-progress since I temporarily disabled lots of code handling messages (i.e. instruments are no longer functional and mock messages have been crippled).

**Comment by chernetsov** [comment]
@jodersky Sorry for being slow on my end. I decided to start with adding includes feature to sbt-mavlink – see pull request https://github.com/jodersky/sbt-mavlink/pull/2

Also was playing with the debugger with my drone messages going into vfd (still with old dialect, just trying to understand completely all the pieces).

Please throw me a hint if I can proceed with wip/mavlink-commn reenabling controls working with official common dialect tomorrow or you are already on it.

Thank you!

**Comment by jodersky** [comment]
Sure, it would be great if you re-enabled the instruments to accept the new messages. I'll be experimenting with the UI for the next couple of days

btw, your pull request in sbt-mavlink is merged in and I published a new version (0.5.0) to maven
